1 improvement provide more configuration options for elasticsearch client
pimcore/elasticsearch-client pull request #7
Opened 2022-11-14 08:38 UTC by Corepex

resolves #1

2022-11-14 09:01 UTC, Corepex commented
I have read the CLA Document and I hereby sign the CLA

2022-11-14 10:25 UTC, fashxp requested changes

2022-11-14 10:25 UTC, fashxp commented on doc/01_Installation.md
> +# Installation
is that really necessary ... we would have already all the information in the [README.md](https://github.com/pimcore/elasticsearch-client/blob/1.x/README.md)

2022-11-14 10:25 UTC, fashxp commented on doc/02_Configuration.md
> +Following you see all the available configuration options for a custom es client.
is that really necessary ... we should update the information in the [README.md](https://github.com/pimcore/elasticsearch-client/blob/1.x/README.md) ... then this should not be necessary anymore

2022-11-15 09:13 UTC, Corepex commented on doc/02_Configuration.md
> +Following you see all the available configuration options for a custom es client.
updated the configuration in README.md - removed the separate file since it's not needed anymore

2022-11-15 09:14 UTC, Corepex commented on doc/01_Installation.md
> +# Installation
added the composer command to the main README - removed the separate file

2022-11-16 12:48 UTC, fashxp approved these changes

2022-11-16 12:49 UTC, merged